### ISSUE TITLE
Test code against preferred version of glatos

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/otn-workshop-base#10]
Caitlin reported problems with the newer version of glatos in some of the code for episode 8. I'm making this ticket as a bucket for ongoing work towards resolving code conflicts between glatos and our code. We can add to it or fork new issues as suits us.

**Comment by jdpye** [comment]
tracking some of the issues found with glatos over in https://github.com/ocean-tracking-network/glatos/issues/

**Comment by CaitlinBate** [comment]
i think this is done now that the PRs for glatos-splits have been accepted? the code works with the current glatos version
