### ISSUE TITLE
Overhauled Animation Lesson

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/otn-workshop-base#22]
The OTNSPG lesson on interactive data exploration and animation (https://github.com/ocean-tracking-network/2020-07-16-OTNSPG-R-workshop/blob/gh-pages/_episodes/06-r-telemetry-animating-ggplot.md) is something that in general we'd like to keep around, but the methods in the lesson are not the way we'd prefer to do it. We have to do some investigation into exactly how we would prefer to do it, and then write a comparable lesson around that.

**Comment by jackVanish** [comment]
There's a dplyr/gganimate lesson in the Brownscombe workshop; it's probably outdated but may have info to mine for this ticket: https://ocean-tracking-network.github.io/jb-acoustic-telemetry/08-advanced-plotting/index.html

**Comment by jackVanish** [comment]
Same goes for this, this time with mapview, ggmap and gganimate. Again, may be outdated but useful. https://ocean-tracking-network.github.io/jb-acoustic-telemetry/10-animating-animal-movements/index.html

**Comment by CaitlinBate** [comment]
people really like animations, i think we prioritize an animation lesson/revamping animation lesson for the new year

**Comment by jackVanish** [comment]
Originally we tapped @jdpye to dig through the lessons linked above and get something teachable out of it, do we need to hand it off to @SoftwareMonk or myself or should it stay on Jon's plate?

**Comment by jackVanish** [comment]
Assigning to Patrick and myself following today's data meeting. I'll let him take the lead on it so I can focus on the other OTW tickets and Remora but I'll be around for helping to write the lesson text and smoke-test the code.

**Comment by CaitlinBate** [comment]
looks like @PatrickWMartin started from this and is moving it along. Branch will be available soon https://ocean-tracking-network.github.io/jb-acoustic-telemetry/10-animating-animal-movements/index.html

**Comment by CaitlinBate** [comment]
this lesson is finished
