### ISSUE TITLE
Lesson revamp - Network Analysis using detections of animals at stations

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/otn-workshop-base#28]
Network analysis as borrowed from JB and RL curricula has a good onramp to getting our data format into a directed or undirected graph, but we don't have a lot of authoritative advice on what a user should do next with that data.

 Until we find a paper we want to teach from to take those next steps, we should park the network analysis lesson.

**Comment by jackVanish** [comment]
This ticket's been open now for almost two years, and since the status is pretty much "Park it till we find something we want to teach," I'm going to close it down and when we get a Network Analysis lesson we want, we'll make a new ticket to track the deliverable.
