### ISSUE TITLE
Retired lesson content

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#29]
Retired BRT material
- https://ocean-tracking-network.github.io/2021-04-13-act-workshop/12-brt-intro/index.html

Retired HMM material
- https://github.com/kimwhoriskey/swim/
- https://ocean-tracking-network.github.io/2020-03-11-DFOBIO-telemetry-workshop/11-hidden-markov-models/index.html
- https://ocean-tracking-network.github.io/2020-03-11-DFOBIO-telemetry-workshop/12-hmm-accounting-for-acf/index.html
- https://ocean-tracking-network.github.io/2020-03-11-DFOBIO-telemetry-workshop/13-hmm-choosing-between-numbers-of-states/index.html

Retired Desicion tree material
- https://ocean-tracking-network.github.io/2020-07-16-OTNSPG-R-workshop/12-kim-whoriskey-analysis-decision-tree/index.html

Going away forever
- https://ocean-tracking-network.github.io/2020-07-16-OTNSPG-R-workshop/14-charles-bangley-applying-telemetry-to-decision-making/index.html 

Staying in main-branch
- https://ocean-tracking-network.github.io/2021-04-13-act-workshop/10-actel-intro/index.html
- https://ocean-tracking-network.github.io/2021-04-13-act-workshop/11-act-actel/index.html

anything retired: gets its own branch

**Comment by jackVanish** [comment]
Retired BRT content is now in its own branch here: https://github.com/ocean-tracking-network/otn-workshop-base/tree/retired_brt.

**Comment by jackVanish** [comment]
Retired HMM content now has its own branch here: https://github.com/ocean-tracking-network/otn-workshop-base/tree/retired_hmm
