### ISSUE TITLE
"how to fork" wiki

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#35]
here https://github.com/ocean-tracking-network/otn-workshop-base/wiki/Forking-and-website-creation-steps

please complete the instructions in step-by-step, numbered format with any relevant links etc

**Comment by jackVanish** [comment]
Wiki pages filled out, here: https://github.com/ocean-tracking-network/otn-workshop-base/wiki/Forking-and-website-creation-steps @CaitlinBate @naomitress please review at your leisure.

**Comment by CaitlinBate** [comment]
happy with it!
