### ISSUE TITLE
delete code and data from gh-pages

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#36]
code/data is currently in two places, confusing the instructors when they clone

code/data needs to be in master for attendees to clone (they cant clone gh because its got too much confusing stuff in there, and we dont want people to break the website format). only the website setup info needs to be in gh-pages so code/data can be deleted to avoid this duplication.

fyi @naomitress

**Comment by jackVanish** [comment]
PR merged after Caitlin's approval. Closing ticket.
