### ISSUE TITLE
Lesson Revamp - ACT Actel

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/otn-workshop-base#38]
Currently the ACT Actel lesson (episode 11) is geared for ACT/OTN-specific data. The lesson needs to be generalized so that it can fit other types of data for the other node styles we plan to teach.

**Comment by CaitlinBate** [comment]
overlap with #34

**Comment by jackVanish** [comment]
Per the overlap with #34, I say we close this ticket and track the updates that need to happen in that ticket, for the sake of clarity and ticket cleanliness.
