### ISSUE TITLE
Lesson Revamp - Additional Interpolation with VTrack

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/otn-workshop-base#39]
This lesson (https://ocean-tracking-network.github.io/jb-acoustic-telemetry/09-additional-vtrack/index.html) from the JB Acoustic Telemetry workshop needs to be whittled down and ported, per Ryan's comments in https://github.com/ocean-tracking-network/otn-workshop-base/issues/6. Specifically, we need to grab the HRSummary() code and find a way to integrate it into our lessons.

**Comment by CaitlinBate** [comment]
vtrack is dead (rip) maybe there are parallels in remora #42 because people really liked some of the extra vtrack features

**Comment by jackVanish** [comment]
@CaitlinBate Per talking about VTrack in the meeting, do we want to close down this ticket and commit to the Remora lesson in the new year?

**Comment by jackVanish** [comment]
Just remembered Caitlin is on vacation. If VTrack is dead then I'm making the executive decision to close this ticket. We talked about it in the data meeting; VTrack is all but abandonware at this point and Remora seems to be where they want to be. We've got another ticket open for a Remora lesson so I say we shut this one down.
