### ISSUE TITLE
review day 1 code, for all nodes

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#41]
- needs to be tested for newer versions of R etc. before we start running these again in the future

**Comment by jackVanish** [comment]
Got the latest RStudio and R 4.2.2, I'll test this out

**Comment by jackVanish** [comment]
Since the ACT workshop is coming up, I ran thru the ACT day 1 code first. Didn't run into any errors, but two small things: 

1. I had to unzip the proj58 and proj61 matched detection zips myself- is this something that's accounted for in the workshop? 
2. All the plots seemed OK but when I was plotting the receivers for proj58 and 61, some of them seemed to be just a little inland- is that normal?

**Comment by jackVanish** [comment]
FACT code seems to run fine too; no errors but same question about the plots. In the section plotting with GGMap and plotly some of the points seem a little close to land. Not sure if this is an error or just a plotting artefact. The sections of the map that the plots are using seem to be correct so I'm assuming it's just a minor display flub.

**Comment by jackVanish** [comment]
GLATOS code seems to be fine too.

**Comment by jackVanish** [comment]
One odd thing in the Migramar code: when I plot the GMR detections by station, there are four stations, including one called Darwin_Bus_Stop. When I summarise by station later, there are only three- Darwin_Bus_Stop is missing. I assume this is nothing and my unfamiliarity with the data but I figured I'd flag it.

**Comment by jackVanish** [comment]
I get a couple of weird warnings running the tag summary on line 476 (Migramar) It doesn't seem to derail the code- just warnings after all- but I thought I'd raise it. Viewing the dataframe after it, it looks fine, just missing some data where those Infs show up. The weight column is also all NaNs, but it is that way in the data too, so I figure it's either wrong there or supposed to be that way. 
<img width="625" alt="Screen Shot 2022-12-22 at 3 58 42 PM" src="https://user-images.githubusercontent.com/5347501/209216361-29d667c4-4425-4532-8c72-931826b9ff54.png">

<img width="775" alt="Screen Shot 2022-12-22 at 3 57 23 PM" src="https://user-images.githubusercontent.com/5347501/209216152-da8ead3a-00fa-4a9e-b60c-372f8394c4cd.png">

**Comment by jackVanish** [comment]
OK, absent the stuff I already raised, the MIGRAMAR code seems fine. There are a couple of weird blips to do with the number/name of stations but nothing code breaking, so I assume it's either a flaw in the data or not a flaw at all and I'm just a little overtuned. I ran through the four challenge files too and they're fine as well (unsurprising, most of them are base R, but the node-specific ones are fine). Anyway, the code seems to do just fine in the newest R/RStudio, so unless there are other factors we want to test, I figure we're good here. I'll ask for comment from @jdpye and @CaitlinBate before I close this one down.

**Comment by CaitlinBate** [comment]
> 

one of the stations didnt have any matched detections

**Comment by CaitlinBate** [comment]
> One odd thing in the Migramar code: when I plot the GMR detections by station, there are four stations, including one called Darwin_Bus_Stop. When I summarise by station later, there are only three- Darwin_Bus_Stop is missing. I assume this is nothing and my unfamiliarity with the data but I figured I'd flag it.

one of the stations didnt have any matched detections

**Comment by CaitlinBate** [comment]
> I get a couple of weird warnings running the tag summary on line 476 (Migramar) It doesn't seem to derail the code- just warnings after all- but I thought I'd raise it. Viewing the dataframe after it, it looks fine, just missing some data where those Infs show up. The weight column is also all NaNs, but it is that way in the data too, so I figure it's either wrong there or supposed to be that way. <img alt="Screen Shot 2022-12-22 at 3 58 42 PM" width="625" src="https://user-images.githubusercontent.com/5347501/209216361-29d667c4-4425-4532-8c72-931826b9ff54.png">
> 
> <img alt="Screen Shot 2022-12-22 at 3 57 23 PM" width="775" src="https://user-images.githubusercontent.com/5347501/209216152-da8ead3a-00fa-4a9e-b60c-372f8394c4cd.png">

the warnings for the one Tiger Shark with no measurments are fine, its just failing to take a no "na" average

there are no weights written in the column in the dataset, so theyre all NAN but this is used as an example and is supposed to be there

**Comment by CaitlinBate** [comment]
im bug fixing some these, and other things i found in this ticket: https://github.com/ocean-tracking-network/otn-workshop-base/issues/44
