### ISSUE TITLE
CB reviewing Day 1 code

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#44]
- [x] - setup R file on master not working on my PC, standby
- [x] - program install doc on master is wrong, needs to be changed to [install_instructions (7).docx](https://github.com/ocean-tracking-network/otn-workshop-base/files/10345474/install_instructions.7.docx)
- [x] - day1 act code: the working directory path needs changing to be generic https://github.com/ocean-tracking-network/otn-workshop-base/pull/43
- [x]  - day1 act code: all the det extract datasets are zipped for proj58 (tagger stuff), can we unzip them, or change the code to read from zip?
- [x] - day1 act code: the det extracts for proj61 are CSVs (array extracts). why are they diff format than the tagger ones?
- [x] - day1 act code: linke 226 should have varibale name `proj61_qual_16_17` so we dont overwrite our full dataset? then we need to change all the code to use the variable `proj61_qual_16_17`  instead of `proj61_qual_16_17_full`. OR we can remove all mention of subsetting at all and use the full dataset the whole time (tested this and it works)
- [x] - day1 act code: change map zoom to 6 on line 266
- [x] - day1 act code: add comment to line 585 to intro new section `# number of stations visited, start and end dates, and track length`
- [x] - day1 act code: re-order the OTher Example Plots section to start with Abacus, then MovMap, then the rest
- [x] - day1 fact code: the working directory path needs changing to be generic https://github.com/ocean-tracking-network/otn-workshop-base/pull/43
- [x] - day1 fact code: line 90,. remove mention of "unzipped file" cuz we;re loading in a zipped one
- [x] - day 1 fact code (maybe others): line 344 says 10,000 rows but its actually 100,000 rows
- [x] - day 1 fact code: needs to have guess max 41881 in line 145, 215
- [x] - day1 fact code: re-order the OTher Example Plots section to start with Abacus, then MovMap, then the rest
- [x] - day1 glatos code: the working directory path needs changing to be generic  https://github.com/ocean-tracking-network/otn-workshop-base/pull/43
- [x] - day1 glatos code: change line 93 guess max to 3103. as well as line 212
- [x] - day1 migramar code: remove lines 3-5
- [x] - day 1 migramar code: change path in line 16 to be more generic https://github.com/ocean-tracking-network/otn-workshop-base/pull/43
- [x] - day 1 migramar code: line 98,line 150, line 220++, line 227++, 237, 241, - just list the file name, no path needed https://github.com/ocean-tracking-network/otn-workshop-base/pull/43
- [x] - day1 onigramar code: add comment to line 548 to intro new section `# number of stations visited, start and end dates, and track length`

**Comment by CaitlinBate** [comment]
places to fix:
- R script on master
- R script in lessons of gh-pages

**Comment by jackVanish** [comment]
I'll let you know when swoop in on any of these targets

**Comment by jackVanish** [comment]
I'm gonna knock off the bottom three unchecked ones

**Comment by jackVanish** [comment]
I'll tick them off as I go but they won't be in till I push the commit up

**Comment by CaitlinBate** [comment]
new thing i found: in Othjer Example Plots, the geom density call needs to be needs to be `geom_density2d(linewidth=7, lty=1)`

changing in

- [ ] - act
- [ ] - fact
- [ ] - glatos
- [ ] - migramar

**Comment by jackVanish** [comment]
With all the changes now merged, this ticket can be comfortably closed.
