### ISSUE TITLE
Workshop Consolidation: Jon

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/otn-workshop-base#5]
For each of the following lessons in the workshops, ascertain the following. 
1. Do we want to continue to teach this material, or is it outdated and of no further use? If we want to teach it, where in the curriculum does it fall? (A ballpark is fine, we’re going to have to change the exact numbering once we have all the lessons assembled, so just provide a rough location. 
2. Is the material already covered by a lesson in the ACT workshop? If so, determine whether or not the lessons are worth merging together, or if the redundant lesson should be discarded. If they need merging, merge them. 
3. If the lesson contains code, determine what data we want to run the code on, and ensure that it works. Does the code need to be updated to use different data from the ACT workshop? If we need to add more files to the data folder for the ACT workshop, find and include suitable data. 

Record any observations or thoughts that you have in the comments of this ticket so that we have a unified paper trail for each person. When your review of a particular lesson is done, and that lesson is deleted or merged, in whole or part, into the main workshop code, tick the box next to it. 

Workshop Master Repo: 
https://github.com/ocean-tracking-network/2021-04-13-act-workshop

- [x] "Actel Intro"
- [ ] "ACT Actel" #38 
- [x] "BRT Intro"

OTNSPG R July 16, 2020
https://github.com/ocean-tracking-network/2020-07-16-OTNSPG-R-workshop

- [x] "Spatial Objects" (I'm going to look in on this one too, I think). 
- [ ] #28
- [x] This lesson also contains some lessons from Kim and Chuck, and I figure you're the person to decide what we do with those. I wasn't sure whether or not we want to keep them in, build them out, whatever. Up to you.

March 11 2020 DFOBIO workshop: 
https://github.com/ocean-tracking-network/2020-03-11-DFOBIO-telemetry-workshop

- [x] This one mostly seems to be an earlier version of the above workshop, but it contains a few lessons on Hidden Markov Models. I'm not sure who's best to look at those, but I seem to recall that was Kim's wheelhouse? I leave it to you to decide what we do with these. 

There are also a couple of things that I think everyone should have a look at, just for the sake of deciding what direction it'll go in. 

Master Workshop Repo:
https://github.com/ocean-tracking-network/2021-04-13-act-workshop

- [x] "Other curriculums"
Now would be a good time to just spool through this quickly and make sure it's accurate and up to date, and that there's not anything else we want to add. It looks fine from what I've seen, but as long as we're in workshop brain mode, we might as well make sure. 

Combined Acoustic Telemetry Tool Training: 
https://ocean-tracking-network.github.io/jb-acoustic-telemetry/index.html

- [x] "Introduction to Acoustic Telemetry Data Analysis"
We should take a look at this and ensure that it's consistent and relevant, if we intend to keep it. I'm not sure who gets to pull the trigger on this one, though.

**Comment by jdpye** [comment]
We like the concept of a spatial data lession, with spatial objects and using `sf` and rasters etc etc, but the current codebase should be updated to reflect the giant leaps the packages have made in the last few years.

**Comment by jdpye** [comment]
Network analysis, the basic onramp for our data into the most popular graph format is largely intact (stations as nodes, animals creating edges between them) but we need a few papers describing analysis metrics and outcomes to build that lesson.

**Comment by jdpye** [comment]
Chuck and Kim's presentations, where they don't have code, can be retired to a defunct branch and revived if they are requested again.

**Comment by jdpye** [comment]
The Actel stuff will be staying, needs generalization to other nodes, currently it's written for ACT/OTN specific format.

**Comment by jackVanish** [comment]
Actel intro looks fine since it's using all Actel's example data; I'll make a separate ticket for generalizing the ACT Actel lesson.

**Comment by jackVanish** [comment]
With all the boxes ticked save for two that have been spun off into their own specialized tickets, this ticket should be good to go. Closing now.
