### ISSUE TITLE
fixes:

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#74]
gh-pages:
- "importing" lesson in intro: header needs to have threee ###
- "intro to glatos" lesson: remove Vtrack library
- "instro to glatos" lesson: add MigraMar to list of nodes in text
- "basic viz and plotting" lesson: rename to be "basic viz and plotting with glatos"

**Comment by jackVanish** [comment]
https://github.com/ocean-tracking-network/otn-workshop-base/pull/89 I made a branch and opened a PR since these are quick fixes and we can knock them off, have a look!

**Comment by CaitlinBate** [comment]
"instro to glatos" lesson: add MigraMar to list of nodes in text
- line 473 should say "(at time of writing, FACT, ACT, GLATOS, or MigraMar)."

"importing" lesson in intro: header needs to have threee ###
- line 69, 124, 201 need updating. and maybe the file in here too https://github.com/ocean-tracking-network/otn-workshop-base/pull/87

**Comment by jackVanish** [comment]
https://github.com/ocean-tracking-network/otn-workshop-base/pull/92 New PR to address the above.
