### ISSUE TITLE
Rshiny Lesson

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#75]
**Name of lesson:**

getting data into Rshiny

**Brief description of lesson content:**

**To whom should we talk to help develop lesson content?**

Rob and Ryan

**About how many chapters will constitute this lesson?**

1 or 2

**Has anyone in our network specifically requested this lesson?**

ROb Lennox

**Comment by jackVanish** [comment]
I talked to Rob about this and he has said that we should just close the ticket as it's a matter of interest but at the time there is no appropriate venue for teaching this and it shouldn't be prioritized (especially without a broader discussion). We can always revisit this in the future when we have a better idea of what we want.
