### ISSUE TITLE
rasterize module

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#76]
Rob wants a lesson

**Comment by jackVanish** [comment]
@robertlennox Can you speak to this in more depth and clarify the ask?

**Comment by jackVanish** [comment]
I talked to Rob about this and he has said that we should just close the ticket as it's a matter of interest but at the time there is no appropriate venue for teaching this and it shouldn't be prioritized (especially without a broader discussion). We can always revisit this in the future when we have a better idea of what we want.
