### ISSUE TITLE
CANSSI ECR cleanup

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#83]
i have an issue with https://github.com/ocean-tracking-network/otn-workshop-base/pull/82/files

it overwrote all the ACT lesson material with the OTNy stuff. it should have been appended (in the same way the earlier lessons contain ALL the code for multiple nodes)

issue is isolated to both basic_animations and pathroutr lessons

**Comment by CaitlinBate** [comment]
i made myself a ticket too https://github.com/ocean-tracking-network/otn-workshop-base/issues/84

**Comment by CaitlinBate** [comment]
issue is isolated to both basic_animations and pathroutr lessons

**Comment by jackVanish** [comment]
https://github.com/ocean-tracking-network/otn-workshop-base/pull/88 This is open now; fixes it for the gh-pages branch but does nothing for the code in Master, that's the next step.

**Comment by CaitlinBate** [comment]
> #88 This is open now; fixes it for the gh-pages branch but does nothing for the code in Master, that's the next step.

ill em all on master as part of #84
