### ISSUE TITLE
CANSSI ECR: OTN content integration

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/otn-workshop-base#84]
todo
- [x] - add OTN data and subfolder if needed - was it done here? https://github.com/ocean-tracking-network/otn-workshop-base/pull/82/files (master)
- [x] - add code into the reports lessons for OTN data (master and ghpages)
- [x] - fix stamen maps code from all nodes in reports lessons (master and ghpages)
- [x] - add otn code from animations lessons #83  (master and ghpages)
- [x] - add new MiscYAPs and GAMS lessons - was it done here? https://github.com/ocean-tracking-network/otn-workshop-base/pull/82/files (master and ghpages)
- [ ] - make sure setup gets updated in master and ghpages #80 
- [x] update "other curriculums" based on FACT 2024 version

**Comment by CaitlinBate** [comment]
gh-pages
- adding otn code to: data frames, plotting, imports, array reports, tag reports https://github.com/ocean-tracking-network/otn-workshop-base/pull/87
- edited other curriculums https://github.com/ocean-tracking-network/otn-workshop-base/pull/87
- miscyaps and gams lessons were already added
- animations lessons (basic and pathroutr) being fixed here #83 
- TODO: stamen maps fix #86 
- TODO: setup fixes #80 

master
- TODO: add otn code folder, add otn data folder
- TODO: stamen maps fix #86 
- TODO: setup fixes #80

**Comment by jackVanish** [comment]
The miscYAPS/GAMS lessons were added but it looks like the code never made it back into Master. I'll move it over now.

**Comment by jackVanish** [comment]
Branch open! https://github.com/ocean-tracking-network/otn-workshop-base/pull/90

**Comment by CaitlinBate** [comment]
TODOs remaining:
- stamen map issues
- setup issues

on BOTH gh-pages and master

**Comment by jackVanish** [comment]
Stadiamaps integration branches:
https://github.com/ocean-tracking-network/otn-workshop-base/pull/94
https://github.com/ocean-tracking-network/otn-workshop-base/pull/93

One for gh-pages, one for master! Review at your leisure.

**Comment by CaitlinBate** [comment]
last TODO is #80 which is held in its own ticket - closing this one woooooo
